### PR TITLE
Add LMStudio Model Selection

### PR DESCRIPTION
**Pull request by tobiashochguertel**
I hope this is so far fine?

### CODE REVIEW

**Comment by stephanj** [comment]
Great feature which almost works perfectly! 

There's one corner case where when you stop the LMStudio server when IDEA is already running and select another LLM provider (for example Ollama) and then go back to LMStudio the "is LMStudio running" check is not executed again.  As a result you'll get an exception.

Screenshot 2024-08-23 at 17 33 47

**Comment by stephanj** [comment]
The model selection works and also the first time check if LMStudio is running.
Screenshot 2024-08-23 at 17 32 25
Screenshot 2024-08-23 at 17 34 09

**Comment by stephanj** [comment]
BTW See also #234 maybe this is something you can easily pickup? 😅 #ThankYou

**Comment by tobiashochguertel** [comment]
Hey @stephanj, thanks for your time to check my PR. 🍀🙏🏻👍

I will work tomorrow on your suggestions and fix the bug 🐛 and then I will work on getting the token usage into the response panel.

**Pull request merged**
