### PR TITLE
Restore the last selected language model from persistent storage.

### LINKED ISSUE #181: Last selected LLM provider is not persisted anymore
Using DevoxxGenie 0.2.5

1. Select LMStudio
2. Switch to another project or open a new IntelliJ window
3. The LLM provider Ollama is selected. Before, the last selected LLM provider was persisted

It also occurs when I have selected GPT4All. It seems that always Ollama is selected when starting an IntelliJ instance.

### PR DESCRIPTION
**Pull request by mydeveloperplanet**
Fixes #181 

I tested it again thoroughly, but maybe you should first test it in the branch to see whether I missed something (again...).

### CODE REVIEW

**Review by stephanj — COMMENTED** [review]
The language model is restored but when I have two projects open, the two combo boxes are hidden for some unknown reason.  👇🏼
https://github.com/user-attachments/assets/3612cb09-5ced-43c7-8157-483f02752b0c

**Comment by mydeveloperplanet** [comment]
ok, reproduced it, will take a look at it

**Comment by stephanj** [comment]
I think I've fixed it... give me a bit more time to test it

**Comment by stephanj** [comment]
```
private void onStateLoaded() {

        if (!isInitializationComplete) {
            lastSelectedProvider = DevoxxGenieStateService.getInstance().getSelectedProvider(project);
            lastSelectedLanguageModel = DevoxxGenieStateService.getInstance().getSelectedLanguageModel(project);

            setupUI();
            restoreLastSelectedProvider();
            restoreLastSelectedLanguageModel();
            isInitializationComplete = true;
        }
    }
```

I did have to add the project related lastSelectedModel otherwise it the 2nd project loads the first project provider & model :)

**Comment by stephanj** [comment]
Fixed and merged.  Can you double check if it works for you with multiple IDEA projects?  #Thanks

**Comment by mydeveloperplanet** [comment]
Works like a charm :+1:

**Pull request merged**
