### PR TITLE
Issue 243 : [REFACTORING] Make ChatResponsePanel more modular

### PR DESCRIPTION
**Pull request by samkerr4coding**
Hello @stephanj Trying to go on this [ issue 243](https://github.com/devoxx/DevoxxGenieIDEAPlugin/issues/243)

Creation of distinctive panels objects for elements structuring ChatResponsePanel, we have a chatresponsePanel sub package  (i dont know if this is a great idea at all but the number of panels class is starting to be consequent), so we have:
- a FileListPanel
- a MetricsExecutionPanel
- ResponseContentPanel
- ResponseHeaderPanel
- SemanticSearchReferencesPanel

+ deletion of unused WarningPanel

Let me know if this is not good

### CODE REVIEW

**Comment by stephanj** [comment]
Looks great! The more smaller/manageable classes we have, the better.  #Thanks

**Comment by stephanj** [comment]
Just noticed that the output panel now has some sort of top padding and some strange cut-off in the footer.

Top of panel
image

Bottom panel cut-off
image

**Comment by samkerr4coding** [comment]
Hello @stephanj will check and fix this ASAP

**Comment by samkerr4coding** [comment]
Hello @stephanj i did create a new PR including a set composed of 2 commit waves (one for the rollback + one for the fixed UI code with the expected modularity), normally it should be ok. Please let me know if it's ok for you

**Pull request merged**
